-- MCP short-link table: opaque, unguessable IDs that resolve to a Supabase storage path.
-- Used by the MCP get_screenshots tool to return short URLs (under 100 chars) so consumers
-- with URL-length limits (Claude Design's web_fetch) can fetch screenshot images.

CREATE TABLE IF NOT EXISTS public.mcp_image_links (
  id          TEXT PRIMARY KEY,                       -- 16-char base62 ID, generated by edge function
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bucket      TEXT NOT NULL DEFAULT 'screenshots',
  path        TEXT NOT NULL,                          -- storage path within the bucket (no leading slash)
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '24 hours'),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.mcp_image_links ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.mcp_image_links TO service_role;

-- Speed up the redirect endpoint's lookup (id is PK so already indexed).
-- Speed up future cleanup jobs.
CREATE INDEX IF NOT EXISTS idx_mcp_image_links_expires ON public.mcp_image_links(expires_at);
CREATE INDEX IF NOT EXISTS idx_mcp_image_links_user ON public.mcp_image_links(user_id);
