/** Terms of use page */
export const terms = {
  en: {
    termsTitle: "Terms of Use for Qualia",
    termsLastUpdated: "Last updated: 20 May 2026",
    termsSection1Title: "Acceptance of Terms",
    termsSection1Body:
      "By accessing or using Qualia (“Service”), you agree to be bound by these Terms of Use (“Terms”). If you do not agree to these Terms, do not use the Service. The Service is operated by Andrea De Iturbe (“we”, “us”, “our”), located in <your-city>, <your-country>. We may update these Terms from time to time; continued use after changes constitutes acceptance of the revised Terms.",
    termsSection2Title: "Description of the Service",
    termsSection2Intro:
      "Qualia is a design-review and UX analysis platform that allows you to:",
    termsSection2Item1:
      "Connect design files via the Figma API (using a personal access token you provide) or upload screenshots directly.",
    termsSection2ItemPlugin:
      "Use the Qualia Figma plugin to run audits directly from Figma: the plugin exports the frames you select and sends them to our backend for the same AI-powered analysis.",
    termsSection2Item2:
      "Run AI-powered audits on single screens or multi-step user flows (e.g. up to a limited number of screens per flow as specified in the product).",
    termsSection2Item3:
      "Define product context, user personas, and constraints to tailor analyses.",
    termsSection2Item4:
      "Optionally connect Notion and/or Google (including Google Drive) via OAuth in read-only mode to link context (e.g. notes, documents) from those services for use within Qualia.",
    termsSection2Item5:
      "Receive scored reports and suggestions generated by automated analysis. Such outputs are for informational and design-support purposes only and do not constitute professional or legal advice.",
    termsSection2Outro:
      "We may impose usage limits (e.g. per-provider frame caps for multi-image audits, or rate limits) for performance and infrastructure reasons. Feature set and limits are described in the product and may change with notice where appropriate.",
    termsSection3Title: "Account and Eligibility",
    termsSection3Body:
      "You must create an account to use the Service. You agree to provide accurate and complete registration information and to keep your account credentials secure. You are responsible for all activity under your account. You must be at least 16 years of age (or the age of digital consent in your jurisdiction, if higher) to use the Service. By using the Service, you represent that you meet these requirements.",
    termsSection4Title: "Third-Party Integrations",
    termsSection4Intro:
      "Your use of third-party services in connection with Qualia is subject to the respective provider’s terms and policies. We do not control and are not responsible for their services. Our backend and data storage are provided by Supabase; for details see our Privacy Policy.",
    termsSection4ItemFigma:
      "Figma: Use of the Figma API (including any token you provide) and of the Qualia Figma plugin must comply with Figma’s terms and policies. You are responsible for the scope and security of your token and for the data you choose to export via the plugin.",
    termsSection4ItemNotionGoogle:
      "Notion and Google (including Drive): If you connect your Notion and/or Google account(s) via OAuth, we request read-only access to link context (e.g. notes, documents) within Qualia. We do not modify, delete, or publish content in your Notion or Google accounts. Your use of these integrations must comply with Notion’s and Google’s respective terms of service. You may revoke access at any time through your account or the provider’s settings.",
    termsSection5Title: "Acceptable Use",
    termsSection5Intro:
      "You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not:",
    termsSection5Item1:
      "Use the Service in any way that violates applicable laws or third-party rights.",
    termsSection5Item2:
      "Attempt to gain unauthorized access to the Service, other accounts, or our or any third party’s systems or data.",
    termsSection5Item3:
      "Use the Service to transmit malware, spam, or any harmful or illegal content.",
    termsSection5Item4:
      "Resell, sublicense, or commercially exploit the Service or its outputs in a manner that competes with or undermines Qualia, unless otherwise agreed in writing.",
    termsSection5Item5:
      "Reverse engineer, decompile, or attempt to derive source code from the Service (except to the extent permitted by mandatory law).",
    termsSection5Outro:
      "We may suspend or terminate access if we reasonably believe you have breached these Terms or acceptable use.",
    termsSection6Title: "Intellectual Property and Your Content",
    termsSection6Body1:
      "You retain ownership of the content you upload or link (designs, screenshots, documents, and any other materials). By using the Service, you grant us a limited, non-exclusive, royalty-free license to use, process, store, and transmit your content solely to provide and improve the Service (including generating analyses and operating integrations such as Figma, Notion, and Google). We do not use your content to train AI models for purposes unrelated to providing the Service to you, as further described in our Privacy Policy.",
    termsSection6Body2:
      "The Service, including its software, design, and branding, is owned by us or our licensors. You receive no right to our intellectual property except the limited right to use the Service in accordance with these Terms.",
    termsSection7Title: "Disclaimers",
    termsSection7Body:
      "The Service and all analyses, reports, and other outputs are provided “as is” and “as available” without warranties of any kind, whether express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that analyses will be accurate or complete. AI-generated content is for design support and informational purposes only and does not constitute professional, legal, or accessibility advice. You use the Service and rely on any outputs at your own risk.",
    termsSection8Title: "Limitation of Liability",
    termsSection8Body:
      "To the maximum extent permitted by applicable law, we and our affiliates, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, data, or business opportunities, arising out of or in connection with your use of the Service or these Terms. Our total liability for any claims arising from or related to the Service or these Terms shall not exceed the amount you paid us in the twelve (12) months prior to the claim (or one hundred euros (€100) if you have not paid us). Some jurisdictions do not allow certain limitations; in such cases our liability will be limited to the fullest extent permitted by law.",
    termsSection9Title: "Termination",
    termsSection9Body:
      "You may stop using the Service at any time. We may suspend or terminate your access with or without notice for breach of these Terms, for legal or operational reasons, or at our discretion. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive (including intellectual property, disclaimers, limitation of liability, and governing law) will survive termination. We may retain or delete your data in accordance with our Privacy Policy and applicable law.",
    termsSection10Title: "Governing Law and Contact",
    termsSection10Body1:
      "These Terms are governed by the laws of Italy, without regard to conflict of law principles. Any disputes shall be subject to the exclusive jurisdiction of the courts of <your-city>, <your-country>, except where mandatory consumer law requires otherwise.",
    termsSection10Body2:
      "For questions about these Terms or the Service, contact us at qualia.ai.analysis@gmail.com.",
    termsByokTitle: "AI Provider API Keys (\"BYOK\")",
    termsByokIntro:
      "Qualia allows you to provide your own API keys for third-party AI providers (Google Gemini, Anthropic Claude, OpenAI GPT, and others). When you supply such keys:",
    termsByokItem1:
      "You are solely responsible for any charges, fees, or quota usage incurred on your provider account.",
    termsByokItem2a: "Qualia stores your keys",
    termsByokItem2Bold: "encrypted at rest",
    termsByokItem2b: "(AES-256 via Supabase) and uses them only to make requests on your behalf when you trigger an audit.",
    termsByokItem3a: "Qualia",
    termsByokItem3Bold: "disclaims all liability",
    termsByokItem3b: "for any unauthorized use, breach, or accidental disclosure of your keys, to the maximum extent permitted by law.",
    termsByokItem4:
      "You may revoke a key at any time from Settings → AI Providers. Revocation deletes the encrypted value from our database; we cannot recover the plaintext.",
    termsByokItem5:
      "You are responsible for ensuring you have the right to use the keys (e.g., your employer's keys with their permission).",
  },
  it: {
    termsTitle: "Termini di utilizzo di Qualia",
    termsLastUpdated: "Ultimo aggiornamento: 20 maggio 2026",
    termsSection1Title: "Accettazione dei Termini",
    termsSection1Body:
      "Accedendo o utilizzando Qualia (“Servizio”), accetti di essere vincolato da questi Termini di utilizzo (“Termini”). Se non accetti questi Termini, ti preghiamo di non utilizzare il Servizio. Il Servizio è gestito da Andrea De Iturbe (“noi”), con sede a <your-city>, <your-country>. Possiamo aggiornare periodicamente questi Termini; l’uso continuato del Servizio dopo le modifiche costituisce accettazione dei Termini aggiornati.",
    termsSection2Title: "Descrizione del Servizio",
    termsSection2Intro:
      "Qualia è una piattaforma di revisione del design e analisi UX che ti permette di:",
    termsSection2Item1:
      "Collegare file di design tramite le API di Figma (usando un token di accesso personale fornito da te) oppure caricare direttamente schermate.",
    termsSection2ItemPlugin:
      "Usare il plugin Qualia per Figma per eseguire audit direttamente da Figma: il plugin esporta i frame che selezioni e li invia al nostro backend per la stessa analisi basata su AI.",
    termsSection2Item2:
      "Eseguire audit basati su AI su singole schermate o su flussi utente multi-step (ad esempio fino a un numero limitato di schermate per flusso, come indicato nel prodotto).",
    termsSection2Item3:
      "Definire contesto di prodotto, personae utente e vincoli per personalizzare le analisi.",
    termsSection2Item4:
      "Collegare facoltativamente Notion e/o Google (incluso Google Drive) tramite OAuth in sola lettura per collegare contesto (es. note, documenti) da tali servizi all’interno di Qualia.",
    termsSection2Item5:
      "Ricevere report con punteggi e suggerimenti generati da analisi automatizzate. Tali output hanno solo finalità informative e di supporto al design e non costituiscono consulenza professionale o legale.",
    termsSection2Outro:
      "Possiamo imporre limiti di utilizzo (ad es. limiti per provider sul numero di frame negli audit multi-immagine, o limiti di rate) per ragioni di performance e infrastruttura. Le funzionalità e i limiti sono descritti nel prodotto e possono cambiare con preavviso ove opportuno.",
    termsSection3Title: "Account ed Idoneità",
    termsSection3Body:
      "Per utilizzare il Servizio è necessario creare un account. Ti impegni a fornire informazioni di registrazione accurate e complete e a mantenere sicure le credenziali del tuo account. Sei responsabile di tutte le attività svolte tramite il tuo account. Devi avere almeno 16 anni (o l’età di consenso digitale prevista nel tuo ordinamento, se superiore) per utilizzare il Servizio. Utilizzando il Servizio dichiari di soddisfare tali requisiti.",
    termsSection4Title: "Integrazioni di Terze Parti",
    termsSection4Intro:
      "L’uso di servizi di terze parti in connessione con Qualia è soggetto ai termini e alle policy dei relativi provider. Non controlliamo né siamo responsabili per tali servizi. Il backend e lo storage dei dati sono forniti da Supabase; per i dettagli consulta la nostra Informativa sulla Privacy.",
    termsSection4ItemFigma:
      "Figma: L’uso delle API di Figma (incluso qualsiasi token che fornisci) e del plugin Qualia per Figma deve essere conforme ai termini e alle policy di Figma. Sei responsabile dell’ambito e della sicurezza del tuo token e dei dati che scegli di esportare tramite il plugin.",
    termsSection4ItemNotionGoogle:
      "Notion e Google (incluso Drive): Se colleghi il tuo account Notion e/o Google tramite OAuth, richiediamo accesso in sola lettura per collegare contesto (es. note, documenti) all’interno di Qualia. Non modifichiamo, eliminiamo o pubblichiamo contenuti nei tuoi account Notion o Google. L’uso di queste integrazioni deve essere conforme ai rispettivi termini di servizio di Notion e Google. Puoi revocare l’accesso in qualsiasi momento dal tuo account o dalle impostazioni del provider.",
    termsSection5Title: "Uso Consentito",
    termsSection5Intro:
      "Ti impegni a utilizzare il Servizio solo per scopi leciti e in conformità con questi Termini. Non devi:",
    termsSection5Item1:
      "Utilizzare il Servizio in modo contrario alle leggi applicabili o ai diritti di terzi.",
    termsSection5Item2:
      "Tentare di ottenere accesso non autorizzato al Servizio, ad altri account o ai sistemi o dati nostri o di terze parti.",
    termsSection5Item3:
      "Utilizzare il Servizio per trasmettere malware, spam o qualsiasi contenuto dannoso o illecito.",
    termsSection5Item4:
      "Rivendere, concedere in sublicenza o sfruttare commercialmente il Servizio o i suoi output in modo tale da competere con o danneggiare Qualia, salvo diverso accordo scritto.",
    termsSection5Item5:
      "Effettuare reverse engineering, decompilare o cercare di ricavare il codice sorgente del Servizio (salvo quanto consentito dalla legge inderogabile).",
    termsSection5Outro:
      "Possiamo sospendere o interrompere l’accesso al Servizio se riteniamo ragionevolmente che tu abbia violato questi Termini o le regole di uso consentito.",
    termsSection6Title: "Proprietà Intellettuale e Contenuti",
    termsSection6Body1:
      "Mantieni la titolarità dei contenuti che carichi o colleghi (design, schermate, documenti e qualsiasi altro materiale). Utilizzando il Servizio, ci concedi una licenza limitata, non esclusiva e gratuita a usare, elaborare, archiviare e trasmettere i tuoi contenuti esclusivamente per fornire e migliorare il Servizio (inclusa la generazione di analisi e il funzionamento delle integrazioni come Figma, Notion e Google). Non utilizziamo i tuoi contenuti per addestrare modelli di AI per scopi non collegati all’erogazione del Servizio nei tuoi confronti, come descritto nella nostra Informativa sulla Privacy.",
    termsSection6Body2:
      "Il Servizio, incluso software, design e brand, è di nostra proprietà o dei nostri licenzianti. Non acquisisci alcun diritto sulla nostra proprietà intellettuale, salvo il diritto limitato a utilizzare il Servizio in conformità con questi Termini.",
    termsSection7Title: "Esclusioni di Responsabilità",
    termsSection7Body:
      "Il Servizio e tutte le analisi, i report e gli altri output sono forniti “così come sono” e “come disponibili”, senza garanzie di alcun tipo, espresse o implicite. Non garantiamo che il Servizio sarà ininterrotto o privo di errori, né che le analisi saranno accurate o complete. I contenuti generati da AI hanno solo finalità informative e di supporto al design e non costituiscono consulenza professionale, legale o in materia di accessibilità. Usi il Servizio e fai affidamento sugli output a tuo esclusivo rischio.",
    termsSection8Title: "Limitazione di Responsabilità",
    termsSection8Body:
      "Nella misura massima consentita dalla legge applicabile, noi e le nostre affiliate, direttori, dipendenti e agenti non saremo responsabili per danni indiretti, incidentali, speciali, consequenziali o punitivi, né per perdita di profitti, dati o opportunità di business derivanti da o connessi all’uso del Servizio o a questi Termini. La nostra responsabilità complessiva per qualsiasi reclamo derivante da o connesso al Servizio o a questi Termini non supererà l’importo da te corrisposto nei dodici (12) mesi precedenti il reclamo (o cento euro (€100) se non hai effettuato pagamenti). Alcune giurisdizioni non consentono determinate limitazioni; in tali casi la nostra responsabilità sarà limitata nella misura massima consentita dalla legge.",
    termsSection9Title: "Risoluzione",
    termsSection9Body:
      "Puoi smettere di utilizzare il Servizio in qualsiasi momento. Possiamo sospendere o revocare il tuo accesso con o senza preavviso in caso di violazione di questi Termini, per motivi legali o operativi o a nostra discrezione. Alla risoluzione, il tuo diritto di utilizzare il Servizio cessa immediatamente. Le disposizioni che per loro natura devono sopravvivere (incluse proprietà intellettuale, esclusioni di responsabilità, limitazione di responsabilità e legge applicabile) sopravvivranno alla risoluzione. Possiamo conservare o eliminare i tuoi dati in conformità con la nostra Informativa sulla Privacy e la legge applicabile.",
    termsSection10Title: "Legge Applicabile e Contatti",
    termsSection10Body1:
      "Questi Termini sono regolati dalla legge italiana, fatto salvo il rinvio a norme di conflitto. Eventuali controversie saranno soggette alla giurisdizione esclusiva dei tribunali di <your-city>, <your-country>, salvo diversa previsione obbligatoria a tutela dei consumatori.",
    termsSection10Body2:
      "Per domande su questi Termini o sul Servizio, contattaci all’indirizzo qualia.ai.analysis@gmail.com.",
    termsByokTitle: "Chiavi API dei provider AI (\"BYOK\")",
    termsByokIntro:
      "Qualia consente di fornire le proprie chiavi API per provider AI di terze parti (Google Gemini, Anthropic Claude, OpenAI GPT e altri). Quando fornisci tali chiavi:",
    termsByokItem1:
      "Sei unicamente responsabile di qualsiasi addebito, costo o consumo di quota sul tuo account provider.",
    termsByokItem2a: "Qualia conserva le tue chiavi",
    termsByokItem2Bold: "cifrate a riposo",
    termsByokItem2b: "(AES-256 tramite Supabase) e le usa solo per effettuare richieste per tuo conto quando avvii un audit.",
    termsByokItem3a: "Qualia",
    termsByokItem3Bold: "declina ogni responsabilità",
    termsByokItem3b: "per uso non autorizzato, violazione o divulgazione accidentale delle chiavi, nei limiti consentiti dalla legge.",
    termsByokItem4:
      "Puoi revocare una chiave in qualsiasi momento da Impostazioni → Provider AI. La revoca elimina il valore cifrato dal nostro database; non possiamo recuperare il testo in chiaro.",
    termsByokItem5:
      "Sei responsabile di assicurarti di avere il diritto di usare le chiavi (es. chiavi del datore di lavoro con il loro permesso).",
  },
} as const;

