// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Figma's sandboxed plugin iframes run without `allow-same-origin`, so accessing
 * `window.localStorage` throws a SecurityError at module-evaluation time — crashing
 * the whole app before React mounts (blank white page).  This factory catches that
 * error and falls back to an in-memory store so the app renders normally and the
 * user can still sign in with email/password within the iframe.
 */
function makeSafeStorage(): Pick<Storage, 'getItem' | 'setItem' | 'removeItem'> {
  try {
    window.localStorage.getItem('__q_test__');
    return window.localStorage;
  } catch {
    const mem: Record<string, string> = {};
    return {
      getItem: (key: string) => (Object.prototype.hasOwnProperty.call(mem, key) ? mem[key] : null),
      setItem: (key: string, value: string) => { mem[key] = value; },
      removeItem: (key: string) => { delete mem[key]; },
    };
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: makeSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});